In [1]:
import pandas as pd
import numpy as np

from bs4 import BeautifulSoup, MarkupResemblesLocatorWarning
import re # standard library to use regex
import ast
import fasttext # library for language detection
from IPython.display import display
from pathlib import Path

In [2]:
# Configuration; centralized source of common variables 
TEXT_COLS = ["short_description", "about_the_game", "detailed_description"]
LABEL_COL = "genres"
REL_COLS = ["appid", "name", "detailed_description", "about_the_game", "short_description", "genres"]
CONTENT_GENRES = ["Action", "Adventure", "Massively Multiplayer", "Racing", "RPG", "Simulation", "Sports", "Strategy"]
ADULT_GENRES = ["Nudity", "Sexual Content", "Gore"]
LID_MODEL = fasttext.load_model("lid.176.bin")
SEED = 42
TESTSET_SIZE = 1000
VALSET_SIZE = 1000
OUTPUT_DIR = Path("Data")
step_log = []

# Data Pre-Processing

In [3]:
# read in the dataset
df = pd.read_csv(r'data/games_march2025_cleaned.csv')
df

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,3.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,682,2434,306,80,89916,"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, '...",84,1168020,76,12608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89613,2115110,Outrun Them,2024-02-29,0,3.99,0,The name of the game is literally the game. Ou...,The name of the game is literally the game. Ou...,It's all in the name.. outrun them.,NaN,...,0,0,0,0,0,"{'2D Platformer': 91, 'Runner': 85, 'Platforme...",-1,-1,-1,-1
89614,1174200,Lands of Pharaoh: Episode 1,2020-01-07,0,10.00,0,Join Our Discord Channel About the Game Briefl...,Briefly: Lands of Pharaoh is a third person vi...,Lands of Pharaoh is a multi-camera-angle based...,NaN,...,0,0,0,0,0,"{'Action': 43, 'Adventure': 41, 'Indie': 41, '...",-1,-1,-1,-1
89615,1160190,Player One,2019-10-10,0,1.99,0,Player One is a new 3D game where you take con...,Player One is a new 3D game where you take con...,"3D Game, Thirdperson Platformer",NaN,...,0,0,0,0,0,"{'Indie': 31, 'Early Access': 21}",-1,-1,-1,-1
89616,3380340,DragonRoad,2025-01-25,0,29.99,0,"This is an open world game on 3D, also a m...","This is an open world game on 3D, also a m...","This is an open world game on 3D, Also a missi...",NaN,...,0,0,0,0,0,"{'RPG': 117, 'Action-Adventure': 111, 'Strateg...",-1,-1,-1,-1
89617,763730,Ragtag Adventurers,2018-03-01,0,9.99,0,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a boss rush game that pi...,NaN,...,0,0,0,0,0,"{'Action': 22, 'Indie': 21}",-1,-1,-1,-1

## Descriptive Measures

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   appid                     89618 non-null  int64
 1   name                      89618 non-null  object
 2   release_date              89618 non-null  object
 3   required_age              89618 non-null  int64
 4   price                     89618 non-null  float64
 5   dlc_count                 89618 non-null  int64
 6   detailed_description      89421 non-null  object
 7   about_the_game            89398 non-null  object
 8   short_description         89498 non-null  object
 9   reviews                   10401 non-null  object
 10  header_image              89618 non-null  object
 11  website                   41114 non-null  object
 12  support_url               44110 non-null  object
 13  support_email             78798 non-null  object
 14  windows                   89618 non-null  bool
 15  mac                       89618 non-null  bool
 16  linux                     89618 non-null  bool
 17  metacritic_score          89618 non-null  int64
 18  metacritic_url            3547 non-null   object
 19  achievements              89618 non-null  int64
 20  recommendations           89618 non-null  int64
 21  notes                     16643 non-null  object
 22  supported_languages       89618 non-null  object
 23  full_audio_languages      89618 non-null  object
 24  packages                  89618 non-null  object
 25  developers                89618 non-null  object
 26  publishers                89618 non-null  object
 27  categories                89618 non-null  object
 28  genres                    89618 non-null  object
 29  screenshots               89618 non-null  object
 30  movies                    89618 non-null  object
 31  user_score                89618 non-null  int64
 32  score_rank                39 non-null     float64
 33  positive                  89618 non-null  int64
 34  negative                  89618 non-null  int64
 35  estimated_owners          89618 non-null  object
 36  average_playtime_forever  89618 non-null  int64
 37  average_playtime_2weeks   89618 non-null  int64
 38  median_playtime_forever   89618 non-null  int64
 39  median_playtime_2weeks    89618 non-null  int64
 40  discount                  89618 non-null  int64
 41  peak_ccu                  89618 non-null  int64
 42  tags                      89618 non-null  object
 43  pct_pos_total             89618 non-null  int64
 44  num_reviews_total         89618 non-null  int64
 45  pct_pos_recent            89618 non-null  int64
 46  num_reviews_recent        89618 non-null  int64
dtypes: bool(3), float64(2), int64(19), object(23)
memory usage: 30.3+ MB

In [5]:
df.describe()

,appid,required_age,price,dlc_count,metacritic_score,achievements,recommendations,user_score,score_rank,positive,...,average_playtime_forever,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
count,8.961800e+04,89618.000000,89618.000000,89618.000000,89618.000000,89618.000000,8.961800e+04,89618.000000,39.000000,8.961800e+04,...,8.961800e+04,89618.000000,8.961800e+04,89618.000000,89618.000000,8.961800e+04,89618.000000,8.961800e+04,89618.000000,89618.000000
mean,1.656904e+06,0.183624,7.309623,0.595583,2.903245,20.552333,1.009401e+03,0.032817,99.128205,1.269896e+03,...,1.149119e+02,5.032694,1.147559e+02,5.301814,4.558627,9.833994e+01,45.352418,1.315490e+03,5.231639,15.584581
std,9.168390e+05,1.725594,13.331073,15.351920,14.445358,163.562418,2.204815e+04,1.615149,0.695076,3.181441e+04,...,6.814748e+03,181.100334,8.806711e+03,189.591095,16.538036,5.717544e+03,40.685695,3.542370e+04,22.335358,444.277307
min,2.000000e+01,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,98.000000,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000e+00,-1.000000,-1.000000
25%,8.550525e+05,0.000000,0.990000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,99.000000,1.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,-1.000000,-1.000000e+00,-1.000000,-1.000000
50%,1.524730e+06,0.000000,4.990000,0.000000,0.000000,5.000000,0.000000e+00,0.000000,99.000000,1.000000e+01,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,60.000000,1.500000e+01,-1.000000,-1.000000
75%,2.430852e+06,0.000000,9.990000,0.000000,0.000000,20.000000,0.000000e+00,0.000000,100.000000,5.800000e+01,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,84.000000,8.100000e+01,-1.000000,-1.000000
max,3.542350e+06,21.000000,999.980000,3427.000000,97.000000,9821.000000,4.401572e+06,100.000000,100.000000,7.480813e+06,...,1.462997e+06,18568.000000,1.462997e+06,18568.000000,100.000000,1.212356e+06,100.000000,8.632939e+06,100.000000,96473.000000

In [6]:
df["genres"].head()

0                           ['Action', 'Free To Play']
1    ['Action', 'Adventure', 'Massively Multiplayer...
2               ['Action', 'Strategy', 'Free To Play']
3                              ['Action', 'Adventure']
4                                           ['Action']
Name: genres, dtype: object

In [7]:
duplicates_by_columns = df[df.duplicated(subset=["appid", "name"])]
duplicates_by_columns

Empty DataFrame
Columns: [appid, name, release_date, required_age, price, dlc_count, detailed_description, about_the_game, short_description, reviews, header_image, website, support_url, support_email, windows, mac, linux, metacritic_score, metacritic_url, achievements, recommendations, notes, supported_languages, full_audio_languages, packages, developers, publishers, categories, genres, screenshots, movies, user_score, score_rank, positive, negative, estimated_owners, average_playtime_forever, average_playtime_2weeks, median_playtime_forever, median_playtime_2weeks, discount, peak_ccu, tags, pct_pos_total, num_reviews_total, pct_pos_recent, num_reviews_recent]
Index: []

[0 rows x 47 columns]

## Reduce to relevant columns
The first pre-processing step involves reducing the original dataset to a preselection of relevant columns. This comprises appid, name, detailed_description, about_the_game, short_description, categories, genres, and tags. Any columns beyond these were not included in this subset.

In [8]:
# Create a reduced subset that only contains relevant columns
df = df.loc[:, REL_COLS]
step_log.append({"step": "1 | Variable selection (no records deleted)", "n_rows": len(df)})
df

,appid,name,detailed_description,about_the_game,short_description,genres
0,730,Counter-Strike 2,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","['Action', 'Free To Play']"
1,578080,PUBG: BATTLEGROUNDS,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,"['Action', 'Adventure', 'Massively Multiplayer..."
2,570,Dota 2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...","['Action', 'Strategy', 'Free To Play']"
3,271590,Grand Theft Auto V Legacy,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,"['Action', 'Adventure']"
4,359550,Tom Clancy's Rainbow Six® Siege,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",['Action']
...,...,...,...,...,...,...
89613,2115110,Outrun Them,The name of the game is literally the game. Ou...,The name of the game is literally the game. Ou...,It's all in the name.. outrun them.,"['Indie', 'Early Access']"
89614,1174200,Lands of Pharaoh: Episode 1,Join Our Discord Channel About the Game Briefl...,Briefly: Lands of Pharaoh is a third person vi...,Lands of Pharaoh is a multi-camera-angle based...,"['Action', 'Adventure', 'Indie', 'Strategy']"
89615,1160190,Player One,Player One is a new 3D game where you take con...,Player One is a new 3D game where you take con...,"3D Game, Thirdperson Platformer","['Indie', 'Early Access']"
89616,3380340,DragonRoad,"This is an open world game on 3D, also a m...","This is an open world game on 3D, also a m...","This is an open world game on 3D, Also a missi...","['Adventure', 'RPG', 'Simulation', 'Strategy']"
89617,763730,Ragtag Adventurers,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a boss rush game that pi...,"['Action', 'Indie']"

## Clean HTML
In this step, the relevant text based columns 'short_description', 'about_the_game', and 'detailed_description' are cleaned from HTML code as well as inserted images. As they dont give any meaningful input for the LLM in the following experiment and thus just bloat the amount of input tokens needed.

In [9]:
def clean_html(text):
    if pd.isna(text):
        return np.nan
        
    soup = BeautifulSoup(text, "html.parser")
    for tag in soup(["img", "video", "source", "script", "style"]):
        tag.decompose()                           # delete media and code in text based columns
    text = soup.get_text(separator="\n")          # Tags weg, Entities dekodiert
    text = re.sub(r"[ \t\xa0]+", " ", text)       # Leerzeichen in Zeilen zusammenfassen
    text = re.sub(r"\s*\n\s*", "\n", text)        # Leerzeilen zusammenfassen
    return text.strip()

In [10]:
for col in TEXT_COLS:
    df[col] = df[col].apply(clean_html)
step_log.append({"step": "2 | HTML Cleanup (no records deleted)", "n_rows": len(df)})

In [11]:
df

,appid,name,detailed_description,about_the_game,short_description,genres
0,730,Counter-Strike 2,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","['Action', 'Free To Play']"
1,578080,PUBG: BATTLEGROUNDS,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,"['Action', 'Adventure', 'Massively Multiplayer..."
2,570,Dota 2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...","['Action', 'Strategy', 'Free To Play']"
3,271590,Grand Theft Auto V Legacy,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,"['Action', 'Adventure']"
4,359550,Tom Clancy's Rainbow Six® Siege,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",['Action']
...,...,...,...,...,...,...
89613,2115110,Outrun Them,The name of the game is literally the game. Ou...,The name of the game is literally the game. Ou...,It's all in the name.. outrun them.,"['Indie', 'Early Access']"
89614,1174200,Lands of Pharaoh: Episode 1,Join Our Discord Channel About the Game Briefl...,Briefly: Lands of Pharaoh is a third person vi...,Lands of Pharaoh is a multi-camera-angle based...,"['Action', 'Adventure', 'Indie', 'Strategy']"
89615,1160190,Player One,Player One is a new 3D game where you take con...,Player One is a new 3D game where you take con...,"3D Game, Thirdperson Platformer","['Indie', 'Early Access']"
89616,3380340,DragonRoad,"This is an open world game on 3D, also a missi...","This is an open world game on 3D, also a missi...","This is an open world game on 3D, Also a missi...","['Adventure', 'RPG', 'Simulation', 'Strategy']"
89617,763730,Ragtag Adventurers,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a boss rush game that pi...,"['Action', 'Indie']"

## Drop missing values
Based on the HTML-cleaned data set, all empty or missing entries are now filtered out. This applies to both the TEXT_COL and the LABEL_COL. Generating synthetic or averaged values to fill in the gaps does not make sense in this context.

In [12]:
s = pd.read_csv(r"data/games_march2025_cleaned.csv", usecols=["genres"])["genres"]

print(s.head(10).to_string())
print("Missing (NaN):", s.isna().sum())
print("Proportion in list format:", s.dropna().str.strip().str.startswith("[").mean())

# Check that every instance can be parsed as a list
def parses(x):
    try:
        return isinstance(ast.literal_eval(x), list)
    except (ValueError, SyntaxError):
        return False
print("Can not be parsed:", (~s.dropna().apply(parses)).sum())

0                           ['Action', 'Free To Play']
1    ['Action', 'Adventure', 'Massively Multiplayer...
2               ['Action', 'Strategy', 'Free To Play']
3                              ['Action', 'Adventure']
4                                           ['Action']
5                           ['Action', 'Free To Play']
6              ['Action', 'Adventure', 'Indie', 'RPG']
7    ['Action', 'Adventure', 'Indie', 'Massively Mu...
8                    ['Casual', 'Indie', 'Simulation']
9              ['Action', 'Adventure', 'Free To Play']
Missing (NaN): 0
Proportion in list format: 1.0
Can not be parsed: 0

In [13]:
for col in TEXT_COLS:
    df[col] = df[col].where(df[col].str.strip().astype(bool), np.nan)
 
df[LABEL_COL] = df[LABEL_COL].fillna("[]").apply(ast.literal_eval)
df = df.dropna(subset=TEXT_COLS)
df = df[df[LABEL_COL].str.len() > 0]
step_log.append({"step": "3 | Remove missing values", "n_rows": len(df)})
 
print("\nAll genres featured (for checking the label set):")
print(df[LABEL_COL].explode().value_counts().to_string(), "\n")

All genres featured (for checking the label set):
genres
Indie                    63110
Casual                   38657
Action                   36780
Adventure                35394
Simulation               18548
Strategy                 17338
RPG                      16314
Early Access              9097
Free To Play              8848
Sports                    3932
Racing                    3296
Massively Multiplayer     2113
Utilities                  856
Design & Illustration      494
Violent                    429
Animation & Modeling       394
Education                  389
Video Production           285
Gore                       265
Game Development           256
Audio Production           195
Software Training          191
Photo Editing              149
Web Publishing              99
Nudity                      96
Sexual Content              90
Accounting                  24
Movie                        2
Documentary                  1
Episodic                     1
Short                        1
Tutorial                     1
360 Video                    1

In [14]:
assert df[TEXT_COLS].notna().all().all(), "Descriptions still missing."
assert (df[TEXT_COLS].apply(lambda s: s.str.strip().str.len()) > 0).all().all(), "Descriptions still missing."
assert (df[LABEL_COL].str.len() > 0).all(), "Empty genres remain."
print("All checks passed.")

All checks passed.

## Check for adult content

In [15]:
has_genre = df[LABEL_COL].apply(lambda gs: bool(set(gs).intersection(ADULT_GENRES)))
df = df[~has_genre].copy()
step_log.append({"step": "4 | Remove adult content", "n_rows": len(df)})

## Language filter (check for english only)

In [16]:
LANG_MIN_PROB = {"short_description": 0.85,
                 "about_the_game": 0.85,
                 "detailed_description": 0.85}

In [17]:
def text_chunks(text: str, chunk: int = 1000) -> list[str]:
    """Keep short texts in their entirety and split long texts in the beginning, middle and end."""
    if len(text) <= chunk:
        return [text]
    mid = len(text) // 2
    return [text[:chunk], text[mid - chunk // 2 : mid + chunk // 2], text[-chunk:]]

def is_english(series: pd.Series, min_prob: float) -> pd.Series:
    """True, if all sections of a text are in English with a probability of >= min_prob."""
    chunks = [text_chunks(t) for t in series]
    flat = [c.replace("\n", " ") for cs in chunks for c in cs]   # remove escape sequence as fasttext requires single-line texts
    labels, probs = LID_MODEL.predict(flat, k=1)
    en_prob = [p[0] if l[0] == "__label__en" else 0.0 for l, p in zip(labels, probs)]

    result, i = [], 0
    for cs in chunks:
        result.append(all(p >= min_prob for p in en_prob[i : i + len(cs)]))
        i += len(cs)
    return pd.Series(result, index=series.index)

lang_ok = pd.DataFrame({c: is_english(df[c], p) for c, p in LANG_MIN_PROB.items()})
print("Non-English text per column:")

display((~lang_ok).sum().rename("Count").to_frame())
print("Disagreement between the columns:", (lang_ok.nunique(axis=1) > 1).sum())

# Review of the rejected texts for verification
rejected = df[~lang_ok.all(axis=1)].copy()

# In which column of the game did the language filter fail?
rejected["failed_cols"] = (~lang_ok.loc[rejected.index]).apply(
    lambda r: ", ".join(r.index[r]), axis=1)

def worst_chunk(text: str):
    """Section with the lowest P(en) (probability that the text is english): recognised language, probability, text extract."""
    chunks = [c.replace("\n", " ") for c in text_chunks(text)]
    labels, probs = LID_MODEL.predict(chunks, k=1)
    en = [p[0] if l[0] == "__label__en" else 0.0 for l, p in zip(labels, probs)]
    i = int(np.argmin(en))
    return labels[i][0].replace("__label__", ""), round(float(probs[i][0]), 3), chunks[i][:300]

# Sample table with details for each column
sample = rejected.sample(min(30, len(rejected)), random_state=SEED)
for col in TEXT_COLS:
    sample[[f"{col}_lang", f"{col}_prob", f"{col}_excerpt"]] = (
        sample[col].apply(lambda t: pd.Series(worst_chunk(t))))

pd.set_option("display.max_colwidth", 300)
for col in TEXT_COLS:
    print(f"\n=== {col} ===")
    display(sample.loc[sample["failed_cols"].str.contains(col),
                       ["name", "failed_cols", f"{col}_lang", f"{col}_prob", f"{col}_excerpt"]])

# Overview: Which languages were detected? (by column, failed texts only)
for col in TEXT_COLS:
    failed = rejected[rejected["failed_cols"].str.contains(col)]
    langs = failed[col].apply(lambda t: worst_chunk(t)[0])
    print(f"\nErkannte Sprachen in {col} (n = {len(failed)}):")
    display(langs.value_counts().head(10).rename("Count").to_frame())

# Optional: export everything, e.g. to view in Excel
# rejected[["appid", "name", "failed_cols", *TEXT_COLS]].to_csv(
    # OUTPUT_DIR / "rejected_language.csv", index=False, encoding="utf-8-sig")

df = df[lang_ok.all(axis=1)]
step_log.append({"step": "5 | Language filter (english)", "n_rows": len(df)})

Non-English text per column:

                      Count
short_description     14679
about_the_game         6863
detailed_description   7248

Disagreement between the columns: 15156

=== short_description ===

,name,failed_cols,short_description_lang,short_description_prob,short_description_excerpt
15204,Around the World in 80 days: Hidden Objects,short_description,en,0.816,You will travel round the world with the Jules Verne heroes! Each location (scene) is a new continent or a new country where you will find yourself in the atmosphere of this region thanks to the picturesque and colorful graphics and the unique musical background.
41263,Maxi Pool Masters VR,short_description,en,0.840,Maxi pool Masters takes you inside the action in a fun and innovative pool game.
53182,Devils Adventure,short_description,en,0.808,2.5d Platformer where you control devil character. Mission to avoid traps and enemies and finish different levels and find skulls
10604,Neckbreak,short_description,en,0.842,"An overdose of reality can have dire consequences... Tumble down the rabbit hole and embrace your downfall with 12 endings, non linear day by day progression, sanity system and more..."
86741,Endless Furry Asteroids,"short_description, about_the_game, detailed_description",en,0.717,Welcome to Endless Furry Asteroids! The 6th installment of the 'Endless Furry' Series!
11740,The Sushi Spinnery,short_description,en,0.586,Revolutionize the revolving sushi bar in this fresh new sim!
32160,Oppaidius Desert Island!,"short_description, about_the_game, detailed_description",en,0.841,"W-w-w-whaaaaat...? I'm on a desert island, alone with Angela... NAKED...? Discover what happens next in this original visual novel!"
27580,Moon's Creed,short_description,en,0.755,Choose your zodiac hero. Craft unique decks. Collect astral boons. Vanquish corrupted constellations. Ascend through cosmic chaos!
19427,Eldritchvania,short_description,en,0.828,"Explore unearthly ruins, solve arcane riddles and pick up your sword against the indescribable horrors that lurk amidst the forgotten depths of our world. Beware the creeping grip of madness as you uncover secrets not meant for the eyes of men!"
77269,Winterland,short_description,en,0.554,"This is a short peaceful RPG. Your only commands are 'joke', 'dance', 'stare', 'run away', and 'hug'."
74776,Lethal Operation Episode 3 Lethal Arms of Justice,"short_description, about_the_game, detailed_description",ja,1.000,キャラをじっくり育てながら広い世界を冒険する――。 そんなSTGの最終編。ショットを合成して、いいとこどりのショットも作れる！ シリーズ最強の敵たちに最強の武器やスキルの組み合わせで対抗し、 この物語の真実に辿り着いてください―
55694,Sukebe Beach,short_description,en,0.767,Break all the blocks and collect the images.
4042,Slipways,short_description,en,0.826,Weave isolated planets into a vast trade empire. Hatch plans. Research game-breaking technologies. Still be done in time for lunch. Enjoy the endless possibilities of a space grand strategy game in 60 minutes flat.
88412,Pinball,"short_description, about_the_game, detailed_description",en,0.530,Fantasy Pinball Arcade Games
25119,Meadowland,short_description,en,0.834,"Meadowland is an interactive poem. Explore a world, partake in a story."
37671,JetX VR,short_description,en,0.831,"JetX, new ambitious arena shooter game available on both PC and VR"
74284,Gozenyojinomanimani,"short_description, about_the_game, detailed_description",ja,0.999,「これから私が話すのは、かみさまが作った、にせものの世界の終わりの物語」これは、愛と狂気と猟奇の惑星と——「僕」の終わりの物語。午前４時、終焉を待つ不死鳥と、罪を犯した僕と君の最期のひととき。過去作「偽物ワールズエンド」完結編 最終章「午前４時のまにまに -偽物ワールズエンド-」
39958,Crazy Machines: Golden Gears,short_description,en,0.809,"In this 'Rube-Goldberg' style puzzle game, experiment and build your wacky contraptions with physics action like never before! Experience dazzling visuals of explosives, fire, and true to life physics behavior when you put the experiment into motion!"
15901,SOLAS 128,short_description,en,0.796,"Explore SOLAS 128, a game of interconnected puzzles where you redirect and reconfigure rhythmic pulses of light to breathe life back into an ancient machine. BAFTA Scotland Game Winner."
14142,The Spectrum Retreat,short_description,en,0.806,Check-in to The Spectrum Retreat for a stay you won’t forget. Manipulate your way to the truth in this captivating narrative-driven puzzler.
80496,GUNPIG: Firepower For Hire,short_description,en,0.774,"Sci-fi top-down twin-stick shooter with 9 weapons, 3 alts and secret hidden collectibles!"
14533,Shiren the Wanderer: The Mystery Dungeon of Serpentcoil Island,short_description,en,0.765,A new adventure for Shiren and Koppa begins!
8568,HIS (Heroes In the Sky),"short_description, about_the_game, detailed_description",it,0.457,-
43612,Rurizakura,"short_description, about_the_game, detailed_description",zh,0.935,《瑠璃樱》是新锐日本美少女游戏品牌CANDY VIOLET的处女作。本作由萌木原文武负责人设与原画，雪仁担当编剧，水城新人负责音乐，并由AiRI献唱主题曲。

=== about_the_game ===

,name,failed_cols,about_the_game_lang,about_the_game_prob,about_the_game_excerpt
36575,TAL: Jungle,"about_the_game, detailed_description",en,0.839,"TAL: Jungle - In this game you need to help your hero go through a maze, avoiding traps. Key features: 60 levels Interesting soundtrack 2 heroes to choose from Steam Achievements Contol: W,A,S,D - movement, R - restart, space bar - next level, F4 - fullscreen mode Credits: This game was created ..."
86741,Endless Furry Asteroids,"short_description, about_the_game, detailed_description",en,0.811,"Welcome to Endless Furry Asteroids! The 6th installment of the 'Endless Furry' Series! This game is a simple parody game, but with a furry twist! Key Features: 1. Shoot asteroids into smaller ones. 2. Try to get the best score with limited lives. 3. Do your best to survive as the asteroids incre..."
32160,Oppaidius Desert Island!,"short_description, about_the_game, detailed_description",en,0.824,"with more than 200 hand-drawn animation frames - Legendary composer Keiji Yamagishi (Ninja Gaiden, Captain Tsubasa series, Streets Of Rage 4) joins the game with an original track! - A detailed story with more than 33K words, spanning several different endings! - More than 140 'jiggle breast phy..."
74776,Lethal Operation Episode 3 Lethal Arms of Justice,"short_description, about_the_game, detailed_description",ja,1.000,1時間程度のステージを繰り返し遊ぶのではなく、 キャラをじっくり育てながら広い世界を冒険する――。 そんなSTGがあってもいいじゃないか!! …というコンセプトで始めたリーサルオペレーションの第三弾。 多数の仲間とウェポンを集め、広大な世界を巡り、 世界の裏に用心深く隠れ潜む黒幕の正体を暴け! 同じリーサルオペレーションの「レイ編」「ルギッタ編」と比べ 本作は『気づき』と『力vs力』に比重が置かれています。 よってプレイヤー側の性能はリーサルシリーズ過去最強！ 強力な装備や仲間が大量に存在し ボム的な役割を担うスフィアタイラントも 最終的には4つまで同時に展開可能！ さらにショットとシ...
89601,UC KART,"about_the_game, detailed_description",en,0.581,"UC KART is a racing game for 1 to 4 players. There is HP in the car. When HP reaches zero, the game is over. Equipped with color edit function You can change the color of the car and the driver. Single play support You can play against the CPU. Online play support You can play against other play..."
88412,Pinball,"short_description, about_the_game, detailed_description",en,0.773,"FEATURES • 2 fantasy themed pinball tables with unique graphics, missions system, locations and characters. • Amazing puzzles to solve. • Realistic physics, multi-ball play. • High scores. At the end of each game, have your high score saved. • Unique soundtrack with atmospheric music, sound effe..."
74284,Gozenyojinomanimani,"short_description, about_the_game, detailed_description",ja,1.000,「これから私が話すのは、かみさまが作った、にせものの世界の終わりの物語」 これは、愛と狂気と猟奇の惑星と——「僕」の終わりの物語。 午前４時、終焉を待つ不死鳥と、罪を犯した僕と君の最期のひととき。 過去作「偽物ワールズエンド」完結編 最終章 「午前４時のまにまに -偽物ワールズエンド-」 ●ストーリー 主人公は、かみさま（フェニックス）に憧れてものづくりをしていた、変哲もない作家の端くれだった。 午前４時、真夜中の公園で出会った、 不思議な少女「フェニ」 「おじさんは、真実を……ほんとうのことを、知りたいって思う？ それとも、知らない方が幸せだって思う？」 主人公は、彼女から不思議な金...
55988,ヘライア祭,"about_the_game, detailed_description",ja,1.000,"「このゲームは個人設定でのコンテンツ許可に基づき、このゲームが表示されています。」 This game may contain content that is not appropriate for all ages or for viewing in the workplace: general adult content. Contains content that is not suitable for all ages, sexual themes. ギリシア神話の女神ヘラ（オリュンポス12神の一人で最高位の女神「結婚、家族、出産の神」）を崇める祭典 女子のみが参加することがで..."
13056,Midnight Scenes: The Highway,"about_the_game, detailed_description",en,0.844,"horror tales with adventure elements by Octavi Navarro (Thimbleweed Park, Photographs...) and Susanna Granell, creators of the critically acclaimed games The Supper , The Librarian , and Unwelcome. Story-driven point-and-click horror experience. Explore, interact with your surroundings, solve p..."
34604,Loot Box,"about_the_game, detailed_description",en,0.843,"Description: Loot Box Clicker is an addictive and rewarding clicker game! Features: Endless Clicker Fun! Gameplay: In Loot Box Clicker, your objective is simple: click to increase your score. Try to beat your personal best!"
41594,DOSMan: Space Aliens in Space!,"about_the_game, detailed_description",en,0.840,"Help Us DOSMan, You are our only hope! FEATURES RETRO SPACE ACTION! Break a leg. Theirs. : Various Alien races & enemy types, including Interstellar Security guards, aliens, mutants and pods. Inside Intel: Interactive informants that provide you clues and hints. Future Soldier: A plethora of fut..."
8568,HIS (Heroes In the Sky),"short_description, about_the_game, detailed_description",it,0.457,-
43612,Rurizakura,"short_description, about_the_game, detailed_description",zh,0.997,故事梗概 时处飞鸟时代。 因代替神树封印妖怪而成为了“神”的少年——命。 为了从妖怪手中拯救世人而成为了除妖舞姬的少女——樱。 少年与少女，背负着永生诅咒的“神”与行将就木的舞姬。 不期而遇的两人所共度的最后二十九个日夜，在此拉开帷幕—— 角色介绍 命 “很遗憾，这里并没有什么神” 背负着永生诅咒的半妖少年。 代替失去力量的神树来封印妖怪。 800年来一直都被诅咒束缚在这片土地上。 樱 “我会在临终前，终结您的生命” 拥有除妖能力的半妖少女。 以生命为代价，通过神舞来降伏妖怪。 在寿命已如风中残烛之时独自踏上了旅途。 制作人员 原画、人设：萌木原文武 编剧：雪仁 音乐：水城新人 制作：...

=== detailed_description ===

,name,failed_cols,detailed_description_lang,detailed_description_prob,detailed_description_excerpt
36575,TAL: Jungle,"about_the_game, detailed_description",en,0.839,"TAL: Jungle - In this game you need to help your hero go through a maze, avoiding traps. Key features: 60 levels Interesting soundtrack 2 heroes to choose from Steam Achievements Contol: W,A,S,D - movement, R - restart, space bar - next level, F4 - fullscreen mode Credits: This game was created ..."
86741,Endless Furry Asteroids,"short_description, about_the_game, detailed_description",en,0.811,"Welcome to Endless Furry Asteroids! The 6th installment of the 'Endless Furry' Series! This game is a simple parody game, but with a furry twist! Key Features: 1. Shoot asteroids into smaller ones. 2. Try to get the best score with limited lives. 3. Do your best to survive as the asteroids incre..."
32160,Oppaidius Desert Island!,"short_description, about_the_game, detailed_description",en,0.824,"with more than 200 hand-drawn animation frames - Legendary composer Keiji Yamagishi (Ninja Gaiden, Captain Tsubasa series, Streets Of Rage 4) joins the game with an original track! - A detailed story with more than 33K words, spanning several different endings! - More than 140 'jiggle breast phy..."
74776,Lethal Operation Episode 3 Lethal Arms of Justice,"short_description, about_the_game, detailed_description",ja,1.000,1時間程度のステージを繰り返し遊ぶのではなく、 キャラをじっくり育てながら広い世界を冒険する――。 そんなSTGがあってもいいじゃないか!! …というコンセプトで始めたリーサルオペレーションの第三弾。 多数の仲間とウェポンを集め、広大な世界を巡り、 世界の裏に用心深く隠れ潜む黒幕の正体を暴け! 同じリーサルオペレーションの「レイ編」「ルギッタ編」と比べ 本作は『気づき』と『力vs力』に比重が置かれています。 よってプレイヤー側の性能はリーサルシリーズ過去最強！ 強力な装備や仲間が大量に存在し ボム的な役割を担うスフィアタイラントも 最終的には4つまで同時に展開可能！ さらにショットとシ...
89601,UC KART,"about_the_game, detailed_description",en,0.581,"UC KART is a racing game for 1 to 4 players. There is HP in the car. When HP reaches zero, the game is over. Equipped with color edit function You can change the color of the car and the driver. Single play support You can play against the CPU. Online play support You can play against other play..."
88412,Pinball,"short_description, about_the_game, detailed_description",en,0.773,"FEATURES • 2 fantasy themed pinball tables with unique graphics, missions system, locations and characters. • Amazing puzzles to solve. • Realistic physics, multi-ball play. • High scores. At the end of each game, have your high score saved. • Unique soundtrack with atmospheric music, sound effe..."
74284,Gozenyojinomanimani,"short_description, about_the_game, detailed_description",ja,1.000,「これから私が話すのは、かみさまが作った、にせものの世界の終わりの物語」 これは、愛と狂気と猟奇の惑星と——「僕」の終わりの物語。 午前４時、終焉を待つ不死鳥と、罪を犯した僕と君の最期のひととき。 過去作「偽物ワールズエンド」完結編 最終章 「午前４時のまにまに -偽物ワールズエンド-」 ●ストーリー 主人公は、かみさま（フェニックス）に憧れてものづくりをしていた、変哲もない作家の端くれだった。 午前４時、真夜中の公園で出会った、 不思議な少女「フェニ」 「おじさんは、真実を……ほんとうのことを、知りたいって思う？ それとも、知らない方が幸せだって思う？」 主人公は、彼女から不思議な金...
55988,ヘライア祭,"about_the_game, detailed_description",ja,1.000,"「このゲームは個人設定でのコンテンツ許可に基づき、このゲームが表示されています。」 This game may contain content that is not appropriate for all ages or for viewing in the workplace: general adult content. Contains content that is not suitable for all ages, sexual themes. ギリシア神話の女神ヘラ（オリュンポス12神の一人で最高位の女神「結婚、家族、出産の神」）を崇める祭典 女子のみが参加することがで..."
13056,Midnight Scenes: The Highway,"about_the_game, detailed_description",en,0.844,"horror tales with adventure elements by Octavi Navarro (Thimbleweed Park, Photographs...) and Susanna Granell, creators of the critically acclaimed games The Supper , The Librarian , and Unwelcome. Story-driven point-and-click horror experience. Explore, interact with your surroundings, solve p..."
34604,Loot Box,"about_the_game, detailed_description",en,0.843,"Description: Loot Box Clicker is an addictive and rewarding clicker game! Features: Endless Clicker Fun! Gameplay: In Loot Box Clicker, your objective is simple: click to increase your score. Try to beat your personal best!"
41594,DOSMan: Space Aliens in Space!,"about_the_game, detailed_description",en,0.840,"Help Us DOSMan, You are our only hope! FEATURES RETRO SPACE ACTION! Break a leg. Theirs. : Various Alien races & enemy types, including Interstellar Security guards, aliens, mutants and pods. Inside Intel: Interactive informants that provide you clues and hints. Future Soldier: A plethora of fut..."
8568,HIS (Heroes In the Sky),"short_description, about_the_game, detailed_description",it,0.457,-
43612,Rurizakura,"short_description, about_the_game, detailed_description",zh,0.997,故事梗概 时处飞鸟时代。 因代替神树封印妖怪而成为了“神”的少年——命。 为了从妖怪手中拯救世人而成为了除妖舞姬的少女——樱。 少年与少女，背负着永生诅咒的“神”与行将就木的舞姬。 不期而遇的两人所共度的最后二十九个日夜，在此拉开帷幕—— 角色介绍 命 “很遗憾，这里并没有什么神” 背负着永生诅咒的半妖少年。 代替失去力量的神树来封印妖怪。 800年来一直都被诅咒束缚在这片土地上。 樱 “我会在临终前，终结您的生命” 拥有除妖能力的半妖少女。 以生命为代价，通过神舞来降伏妖怪。 在寿命已如风中残烛之时独自踏上了旅途。 制作人员 原画、人设：萌木原文武 编剧：雪仁 音乐：水城新人 制作：...

Erkannte Sprachen in short_description (n = 14679):

                   Count
short_description
en                 13011
zh                  1059
ja                   353
ko                    50
ru                    33
fr                    32
pt                    30
es                    27
de                    26
it                     9

Erkannte Sprachen in about_the_game (n = 6863):

                Count
about_the_game
en               5203
zh               1076
ja                341
ko                 52
ru                 42
fr                 27
pt                 26
es                 24
de                 22
pl                  8

Erkannte Sprachen in detailed_description (n = 7248):

                      Count
detailed_description
en                     5578
zh                     1075
ja                      350
ko                       52
ru                       42
fr                       27
pt                       26
es                       25
de                       23
pl                        8

In [18]:
df

,appid,name,detailed_description,about_the_game,short_description,genres
0,730,Counter-Strike 2,"For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical l...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical l...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.","[Action, Free To Play]"
2,570,Dota 2,"The most-played game on Steam. Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, featur...","The most-played game on Steam. Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, featur...","Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has take...","[Action, Strategy, Free To Play]"
3,271590,Grand Theft Auto V Legacy,"When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to surv...","When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to surv...","Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.","[Action, Adventure]"
5,440,Team Fortress 2,"'The most fun you can have online' - PC Gamer Is now FREE! There’s no catch! Play as much as you want, as long as you like! The most highly-rated free game of all time! One of the most popular online action games of all time, Team Fortress 2 delivers constant free updates—new game modes, maps, e...","'The most fun you can have online' - PC Gamer Is now FREE! There’s no catch! Play as much as you want, as long as you like! The most highly-rated free game of all time! One of the most popular online action games of all time, Team Fortress 2 delivers constant free updates—new game modes, maps, e...","Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!","[Action, Free To Play]"
6,105600,Terraria,"Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, machinery, and aesthetics? Perhaps you will choose instead t...","Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, machinery, and aesthetics? Perhaps you will choose instead t...","Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!","[Action, Adventure, Indie, RPG]"
...,...,...,...,...,...,...
89611,1295440,Boom slayer,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents. - 18 LEVELS - Different an...,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents. - 18 LEVELS - Different an...,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents.,"[Adventure, Casual, Indie]"
89612,801660,Swapper Tiles,Swapper Tiles is a first person puzzle game where you play as a robot trapped in a cage with only one way to escape. You must complete all challenges set by your captors. The challenges include complete puzzles by swapping them to create a path between them. This game includes the levels needed ...,Swapper Tiles is a first person puzzle game where you play as a robot trapped in a cage with only one way to escape. You must complete all challenges set by your captors. The challenges include complete puzzles by swapping them to create a path between them. This game includes the levels needed ...,Swapper Tiles is a First Person Puzzle game where you find yourself trapped in a cage with your only chance to escape is to complete the challenges set. The game revolves around completing puzzles by swapping tiles around to create a path between them. Demo available on Steam.,"[Indie, Strategy, Early Access]"
89613,2115110,Outrun Them,"The name of the game is literally the game. Outrun the zombies and don't let them catch you. Your speed increases the further you run, but so do does the zombie's. No two runs are the same as procedurally generated obstacles will keep you on your toes and randomly placed pickup items will be alm...","The name of the game is literally the game. Outrun the zombies and don't let them catch you. Your speed increases the further you run, but so do does the zombie's. No two runs are the same as procedurally generated obstacles will keep you on your toes and randomly placed pickup items will be alm...",It's all in the name.. outrun them.,"[Indie, Early Access]"
89616,3380340,DragonRoad,"This is an open world game on 3D, also a mission centered survival battle game. It includes gameplay such as role-playing, tactical strategy, player cooperation, mission monster fighting, and experience upgrade. The game plot combines Wang Yangming's philosophy of the mind, learning Wang Yangmin...","This is an open world game on 3D, also a mission centered survival battle game. It includes gameplay such as role-playing, tactical strategy, player cooperation, mission monster fighting, and experience upgrade. The game plot combines Wang Yangming's philosophy of the mind, learning Wang Yangmin...","This is an open world game on 3D, Also a mission centered survival battle game. It includes role-playing, tactical strategy, experience upgrade.It has Dozens scenes and combat tasks, allowing players to complete tasks and receive rewards. It support multi people cooperation on network.","[Adventure, RPG, Simulation, Strategy]"
89617,763730,Ragtag Adventurers,"Ragtag Adventurers is a Boss Rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Take on challenging bosses that will test your skills and cooperation to the maximum. Made with a strong 'gameplay first' attitude, the game aims to deliver a fun experience that wil...","Ragtag Adventurers is a Boss Rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Take on challenging bosses that will test your skills and cooperation to the maximum. Made with a strong 'gameplay first' attitude, the game aims to deliver a fun experience that wil...",Ragtag Adventurers is a boss rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Play alone or with friends against challenging bosses that will put your skills to the test.,"[Action, Indie]"

## Reduce the labelset to content genres
In this step, the range of genres is reduced to a predefined set. This involves, for example, removing all non-games like software, as well as rather undefined and unclear genres such as Early Access or Free to Play which do not provide any indication of the game’s content or nature.

In [19]:
df[LABEL_COL] = df[LABEL_COL].apply(lambda gs: sorted(set(gs).intersection(CONTENT_GENRES)))
df = df[df[LABEL_COL].str.len() > 0]
step_log.append({"step": "6 | Reduce set of labels", "n_rows": len(df)})

df

,appid,name,detailed_description,about_the_game,short_description,genres
0,730,Counter-Strike 2,"For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical l...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical l...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",[Action]
2,570,Dota 2,"The most-played game on Steam. Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, featur...","The most-played game on Steam. Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, featur...","Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has take...","[Action, Strategy]"
3,271590,Grand Theft Auto V Legacy,"When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to surv...","When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to surv...","Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.","[Action, Adventure]"
5,440,Team Fortress 2,"'The most fun you can have online' - PC Gamer Is now FREE! There’s no catch! Play as much as you want, as long as you like! The most highly-rated free game of all time! One of the most popular online action games of all time, Team Fortress 2 delivers constant free updates—new game modes, maps, e...","'The most fun you can have online' - PC Gamer Is now FREE! There’s no catch! Play as much as you want, as long as you like! The most highly-rated free game of all time! One of the most popular online action games of all time, Team Fortress 2 delivers constant free updates—new game modes, maps, e...","Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!",[Action]
6,105600,Terraria,"Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, machinery, and aesthetics? Perhaps you will choose instead t...","Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, machinery, and aesthetics? Perhaps you will choose instead t...","Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!","[Action, Adventure, RPG]"
...,...,...,...,...,...,...
89610,2671880,Fortress Defense,"Prepare for an epic battle in Fortress Defense, a thrilling castle wave defense game where you stand as the last line of defense against hordes of relentless enemy skeletons. As the commander of an elite archer squad, your mission is to protect your kingdom from the relentless skeletal onslaught...","Prepare for an epic battle in Fortress Defense, a thrilling castle wave defense game where you stand as the last line of defense against hordes of relentless enemy skeletons. As the commander of an elite archer squad, your mission is to protect your kingdom from the relentless skeletal onslaught...","As the commander of an elite archer squad, your mission is to protect your kingdom from the relentless skeletal onslaught. Upgrade your archers, unlock potent spells, and discover a vast arsenal of specialized arrows to fend off the unending waves of darkness.","[Action, Adventure, Strategy]"
89611,1295440,Boom slayer,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents. - 18 LEVELS - Different an...,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents. - 18 LEVELS - Different an...,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents.,[Adventure]
89612,801660,Swapper Tiles,Swapper Tiles is a first person puzzle game where you play as a robot trapped in a cage with only one way to escape. You must complete all challenges set by your captors. The challenges include complete puzzles by swapping them to create a path between them. This game includes the levels needed ...,Swapper Tiles is a first person puzzle game where you play as a robot trapped in a cage with only one way to escape. You must complete all challenges set by your captors. The challenges include complete puzzles by swapping them to create a path between them. This game includes the levels needed ...,Swapper Tiles is a First Person Puzzle game where you find yourself trapped in a cage with your only chance to escape is to complete the challenges set. The game revolves around completing puzzles by swapping tiles around to create a path between them. Demo available on Steam.,[Strategy]
89616,3380340,DragonRoad,"This is an open world game on 3D, also a mission centered survival battle game. It includes gameplay such as role-playing, tactical strategy, player cooperation, mission monster fighting, and experience upgrade. The game plot combines Wang Yangming's philosophy of the mind, learning Wang Yangmin...","This is an open world game on 3D, also a mission centered survival battle game. It includes gameplay such as role-playing, tactical strategy, player cooperation, mission monster fighting, and experience upgrade. The game plot combines Wang Yangming's philosophy of the mind, learning Wang Yangmin...","This is an open world game on 3D, Also a mission centered survival battle game. It includes role-playing, tactical strategy, experience upgrade.It has Dozens scenes and combat tasks, allowing players to complete tasks and receive rewards. It support multi people cooperation on network.","[Adventure, RPG, Simulation, Strategy]"
89617,763730,Ragtag Adventurers,"Ragtag Adventurers is a Boss Rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Take on challenging bosses that will test your skills and cooperation to the maximum. Made with a strong 'gameplay first' attitude, the game aims to deliver a fun experience that wil...","Ragtag Adventurers is a Boss Rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Take on challenging bosses that will test your skills and cooperation to the maximum. Made with a strong 'gameplay first' attitude, the game aims to deliver a fun experience that wil...",Ragtag Adventurers is a boss rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Play alone or with friends against challenging bosses that will put your skills to the test.,[Action]

## Length of Description Levels

In [20]:
wc = pd.DataFrame({c: df[c].str.split().str.len() for c in TEXT_COLS})

stats = wc.describe(percentiles=[.01, .02, .05, .10, .25, .50, .75, .90, .99]).T
display(stats.style.format("{:.0f}"))

# How many texts fall below the possible limits?
candidates = [3, 5, 10, 15, 20, 30, 50]
display(pd.DataFrame({c: [(wc[c] < t).sum() for t in candidates] for c in TEXT_COLS},
                     index=[f"< {t} words" for t in candidates]))

# What do texts of a certain length look like?
def show_examples(col: str, lo: int, hi: int, n: int = 5):
    sub = df[(wc[col] >= lo) & (wc[col] < hi)]
    print(f"\n=== {col}: {lo}–{hi - 1} words (n = {len(sub)}) ===")
    if sub.empty:
        print("No records.")
        return
    sample = sub.sample(min(n, len(sub)), random_state=SEED)
    table = pd.DataFrame({
        "Game": sample["name"],
        "Words": wc.loc[sample.index, col],
        "Text": sample[col].str.replace("\n", " ").str.slice(0, 300),
    })
    display(table.style
            .hide(axis="index")
            .set_properties(subset=["Text"], **{"text-align": "left", "white-space": "normal"}))

show_examples("short_description", 1, 5)
show_examples("short_description", 5, 10)
show_examples("about_the_game", 1, 10)
show_examples("about_the_game", 10, 30)

            short_description  about_the_game  detailed_description
< 3 words                   7               3                     2
< 5 words                 102               5                     4
< 10 words               1240              14                    14
< 15 words               3742              37                    34
< 20 words               7561              73                    68
< 30 words              18705             194                   187
< 50 words              53520            1221                  1194

=== short_description: 1–4 words (n = 102) ===

=== short_description: 5–9 words (n = 1138) ===

=== about_the_game: 1–9 words (n = 14) ===

=== about_the_game: 10–29 words (n = 180) ===

## Check for overlap between description levels

In [21]:
short, about, detailed = df["short_description"], df["about_the_game"], df["detailed_description"]

def share_contained(part: pd.Series, whole: pd.Series) -> float:
    """The proportion of lines in which `part` is fully contained within `whole`."""
    return np.mean([p in w for p, w in zip(part, whole)])
 
print("Overlap between levels of description:")
print(f"  about == detailed:         {(about == detailed).mean():.1%}")
print(f"  short == about:            {(short == about).mean():.1%}")
print(f"  short == detailed:         {(short == detailed).mean():.1%}")

print(f"  short ist Teil von about:     {share_contained(short, about):.1%}")
print(f"  about ist Teil von short:     {share_contained(about, short):.1%}")

print(f"  short ist Teil von detailed:  {share_contained(short, detailed):.1%}")
print(f"  detailed ist Teil von short:  {share_contained(detailed, short):.1%}")

print(f"  detailed ist Teil von about:  {share_contained(detailed, about):.1%}")
print(f"  about ist Teil von detailed:  {share_contained(about, detailed):.1%}\n")

Overlap between levels of description:
  about == detailed:         90.2%
  short == about:            0.5%
  short == detailed:         0.5%
  short ist Teil von about:     22.1%
  about ist Teil von short:     0.5%
  short ist Teil von detailed:  22.1%
  detailed ist Teil von short:  0.5%
  detailed ist Teil von about:  90.2%
  about ist Teil von detailed:  100.0%

In [22]:
# Relative proportions (in terms of word count) of the descriptive levels
wc = {c: df[c].str.split().str.len() for c in TEXT_COLS}
pairs = [("short_description", "about_the_game"),
         ("short_description", "detailed_description"),
         ("about_the_game", "detailed_description")]
pairs = [(a, b) for a, b in pairs if a in TEXT_COLS and b in TEXT_COLS]

rows = []
for a, b in pairs:
    ratio = wc[b] / wc[a]                       # >1: b is longer than a
    b_longer, a_longer = wc[b] > wc[a], wc[a] > wc[b]
    rows.append({
        "Relation": f"{b} / {a}",
        "Q10": ratio.quantile(.10),
        "Median": ratio.median(),
        "Q90": ratio.quantile(.90),
        "Δ Median": (ratio - 1).median(),                                        # (b − a) / a
        "Ø |Δ| Wörter": (wc[b] - wc[a]).abs().mean(),
        "b > a": b_longer.mean(),
        "b larger by": (wc[b][b_longer] / wc[a][b_longer] - 1).median(),          # only where b > a
        "b == a": (wc[b] == wc[a]).mean(),
        "b < a": a_longer.mean(),
        "a larger by": (wc[a][a_longer] / wc[b][a_longer] - 1).median(),          # only where a > b
    })

print("Proportions (word count):")

ratio_table = pd.DataFrame(rows)
display(ratio_table.style
        .hide(axis="index")
        .format({"Q10": "{:.2f}", "Median": "{:.2f}", "Q90": "{:.2f}",
                 "Δ Median": "{:+.1%}",
                 "Ø |Δ| Wörter": "{:.1f}",
                 "b > a": "{:.1%}", "b larger by": "{:.1%}",
                 "b == a": "{:.1%}",
                 "b < a": "{:.1%}", "a larger by": "{:.1%}"},
                na_rep="–"))

Proportions (word count):

In [23]:
# Drop detailed_description due to similarity with about_the_game
df = df.drop(columns="detailed_description")
TEXT_COLS = [c for c in TEXT_COLS if c != "detailed_description"]
print(f"Remaining description columns: {TEXT_COLS}")

# Remove games where ‘short_description’ and ‘about_the_game’ are fully identical
identical = df["short_description"] == df["about_the_game"]
print(f"short == about: {identical.sum()} Spiele werden entfernt")

df = df[~identical].copy()
step_log.append({"step": "7 | Remove short == about", "n_rows": len(df)})

Remaining description columns: ['short_description', 'about_the_game']
short == about: 310 Spiele werden entfernt

In [24]:
df

,appid,name,about_the_game,short_description,genres
0,730,Counter-Strike 2,"For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2. A free upgrade to CS:GO, Counter-Strike 2 marks the largest technical l...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",[Action]
2,570,Dota 2,"The most-played game on Steam. Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, featur...","Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it's their 10th hour of play or 1,000th, there's always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has take...","[Action, Strategy]"
3,271590,Grand Theft Auto V Legacy,"When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with some of the most frightening and deranged elements of the criminal underworld, the U.S. government and the entertainment industry, they must pull off a series of dangerous heists to surv...","Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.","[Action, Adventure]"
5,440,Team Fortress 2,"'The most fun you can have online' - PC Gamer Is now FREE! There’s no catch! Play as much as you want, as long as you like! The most highly-rated free game of all time! One of the most popular online action games of all time, Team Fortress 2 delivers constant free updates—new game modes, maps, e...","Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!",[Action]
6,105600,Terraria,"Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fortune, and glory. Will you delve deep into cavernous expanses in search of treasure and raw materials with which to craft ever-evolving gear, machinery, and aesthetics? Perhaps you will choose instead t...","Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!","[Action, Adventure, RPG]"
...,...,...,...,...,...
89610,2671880,Fortress Defense,"Prepare for an epic battle in Fortress Defense, a thrilling castle wave defense game where you stand as the last line of defense against hordes of relentless enemy skeletons. As the commander of an elite archer squad, your mission is to protect your kingdom from the relentless skeletal onslaught...","As the commander of an elite archer squad, your mission is to protect your kingdom from the relentless skeletal onslaught. Upgrade your archers, unlock potent spells, and discover a vast arsenal of specialized arrows to fend off the unending waves of darkness.","[Action, Adventure, Strategy]"
89611,1295440,Boom slayer,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents. - 18 LEVELS - Different an...,Boom slayer is an reckless and fun arcade. Your mission is shoot skull to reach the goal. But each level will be more complex and challenging !! Every level has limit of shots that player can use to unlock next level. At each level there are several types of opponents.,[Adventure]
89612,801660,Swapper Tiles,Swapper Tiles is a first person puzzle game where you play as a robot trapped in a cage with only one way to escape. You must complete all challenges set by your captors. The challenges include complete puzzles by swapping them to create a path between them. This game includes the levels needed ...,Swapper Tiles is a First Person Puzzle game where you find yourself trapped in a cage with your only chance to escape is to complete the challenges set. The game revolves around completing puzzles by swapping tiles around to create a path between them. Demo available on Steam.,[Strategy]
89616,3380340,DragonRoad,"This is an open world game on 3D, also a mission centered survival battle game. It includes gameplay such as role-playing, tactical strategy, player cooperation, mission monster fighting, and experience upgrade. The game plot combines Wang Yangming's philosophy of the mind, learning Wang Yangmin...","This is an open world game on 3D, Also a mission centered survival battle game. It includes role-playing, tactical strategy, experience upgrade.It has Dozens scenes and combat tasks, allowing players to complete tasks and receive rewards. It support multi people cooperation on network.","[Adventure, RPG, Simulation, Strategy]"
89617,763730,Ragtag Adventurers,"Ragtag Adventurers is a Boss Rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Take on challenging bosses that will test your skills and cooperation to the maximum. Made with a strong 'gameplay first' attitude, the game aims to deliver a fun experience that wil...",Ragtag Adventurers is a boss rush game that pits 4 heroes against terrible monsters in Shared Screen Multiplayer. Play alone or with friends against challenging bosses that will put your skills to the test.,[Action]

## Label Leakage

In [25]:
# REGEX for each genre
GENRE_PATTERNS = {
    "Action":                [r"action"],
    "Adventure":             [r"adventures?"],
    "Massively Multiplayer": [r"massively[- ]multiplayer", r"mmo(?:rpg|rts|fps)?s?"],
    "RPG":                   [r"rpgs?", r"role[- ]playing"],
    "Racing":                [r"racing", r"racers?"],
    "Simulation":            [r"simulations?", r"simulators?"],
    "Sports":                [r"sports?"],
    "Strategy":              [r"strateg(?:y|ies|ic)"],
}
genre_re = {g: re.compile(r"\b(?:" + "|".join(p) + r")\b", re.IGNORECASE)
            for g, p in GENRE_PATTERNS.items()}

# Leakage flag per game and column
for col in TEXT_COLS:
    df[f"leak_{col}"] = [any(genre_re[g].search(t) for g in gs if g in genre_re)
                         for t, gs in zip(df[col], df[LABEL_COL])]

# Leakage rate per split and description column
print("Leakage Rate (Proportion of games whose text mentions a specific ‘gold’ genre):")
display(pd.DataFrame({"Leakage rate": {c: df[f"leak_{c}"].mean() for c in TEXT_COLS}})
        .style.format("{:.1%}"))

rows = []
for g, rx in genre_re.items():
    has_g = df[LABEL_COL].apply(lambda gs: g in gs)
    rows.append({"Genre": g, "n": has_g.sum(),
                 **{c: df.loc[has_g, c].str.contains(rx).mean() for c in TEXT_COLS}})
print("Leakage rate per genre:")
display(pd.DataFrame(rows).style.hide(axis="index").format({c: "{:.1%}" for c in TEXT_COLS}))

step_log.append({"step": "8 | Label Leakage (no records removed)", "n_rows": len(df)})

Leakage Rate (Proportion of games whose text mentions a specific ‘gold’ genre):

Leakage rate per genre:

## Split Testset

In [26]:
from sklearn.preprocessing import MultiLabelBinarizer
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit

In [27]:
df = df.reset_index(drop=True)
mlb = MultiLabelBinarizer(classes=sorted(CONTENT_GENRES))
Y = mlb.fit_transform(df[LABEL_COL])

def stratified_split(n: int, Y: np.ndarray, size: int):
    splitter = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=size / n, random_state=SEED)
    return next(splitter.split(np.zeros((n, 1)), Y))

# Split off the test set
rest_idx, test_idx = stratified_split(len(df), Y, TESTSET_SIZE)
df_rest, df_test = df.iloc[rest_idx].reset_index(drop=True), df.iloc[test_idx]
Y_rest = Y[rest_idx]

# Split off the validation set from the remainder
train_idx, val_idx = stratified_split(len(df_rest), Y_rest, VALSET_SIZE)
df_train, df_val = df_rest.iloc[train_idx], df_rest.iloc[val_idx]

# Check for disjunction
ids = {"train": set(df_train["appid"]), "val": set(df_val["appid"]), "test": set(df_test["appid"])}
assert ids["train"].isdisjoint(ids["val"]) and ids["train"].isdisjoint(ids["test"]) \
       and ids["val"].isdisjoint(ids["test"]), "Leakage between the splits."

print("Label distribution (proportion of games by genre):")
display(pd.DataFrame({
    "train": Y_rest[train_idx].mean(axis=0),
    "val":   Y_rest[val_idx].mean(axis=0),
    "test":  Y[test_idx].mean(axis=0),
}, index=mlb.classes_).style.format("{:.3f}"))

print("Leakage rate per data split and description column:")
display(pd.DataFrame({name: {c: part[f"leak_{c}"].mean() for c in TEXT_COLS}
                      for name, part in [("train", df_train), ("val", df_val), ("test", df_test)]})
        .style.format("{:.1%}"))

for i, (name, part) in enumerate([("Train", df_train),
                                  ("Validation", df_val),
                                  ("Test", df_test)], start=1):
    step_log.append({"step": f"8.{i} | {name}", "n_rows": len(part)})
print(f"Train: {len(df_train)} | Val: {len(df_val)} | Test: {len(df_test)}")

Label distribution (proportion of games by genre):

Leakage rate per data split and description column:

Train: 57799 | Val: 1003 | Test: 1009

## Save the final datasets & documentation of processing

In [28]:
df_train.to_parquet(OUTPUT_DIR / "train_set.parquet", index=False)
df_val.to_parquet(OUTPUT_DIR / "val_set.parquet", index=False)
df_test.to_parquet(OUTPUT_DIR / "test_set.parquet", index=False)

pd.DataFrame(step_log).to_csv(OUTPUT_DIR / "preprocessing_log.csv", index=False)
print(f"\nSaved in {OUTPUT_DIR.resolve()}")

Saved in C:\Users\Nils\ICL\data